linters-settings:
  lll:
    line-length: 130
  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  enable:
    - staticcheck
    - lll
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
